pull_request_rules:
  - name: delete head branch after merge
    conditions: []
    actions:
      delete_head_branch:

  - name: automatic merge when reviewed and CI passes
    conditions:
      - status-success=continuous-integration/travis-ci/push
      - status-success=continuous-integration/travis-ci/pr
      - '#approved-reviews-by>=1'
      - '#review-requested=0'
      - '#changes-requested-reviews-by=0'
      - '#commented-reviews-by=0'
    actions:
      comment:
        message: Auto-submitting change that passed CI
      merge:
        method: squash

  - name: automatic merge when author is zmbush and CI passes
    conditions:
      - status-success=continuous-integration/travis-ci/push
      - status-success=continuous-integration/travis-ci/pr
      - author=zmbush
    actions:
      comment:
        message: Auto-submitting change that passed CI
      merge:
        method: squash
