language: rust
rust:
  - stable
cache: cargo
services:
  - postgresql
install:
  - rustup component add clippy
  - rustup component add rustfmt
  - nvm install 6
  - npm install -g yarn
  - cargo install --force diesel_cli
  - yarn
before_script:
  - psql -c 'create database budgetron;' -U postgres
  - cp .env.travis .env
  - diesel migration run
  - cargo build
script:
  - yarn run webpack
  - cargo clippy --all -- -D clippy
  - cargo fmt --all -- --write-mode=diff
  - cargo test
