language: rust
rust:
  - stable
  - 1.21.0
cache: cargo
services:
  - postgresql
install:
  - rustup install nightly
  - cargo +nightly install --force rustfmt-nightly
  - cargo +nightly install --force clippy
  - nvm install 6
  - npm install -g yarn
  - cargo install --force diesel_cli
  - (cd web && yarn)
before_script:
  - psql -c 'create database budgetron;' -U postgres
  - cp .env.travis .env
  - diesel migration run
  - cargo build
script:
  - (cd web && yarn run webpack)
  - cargo +nightly fmt --all -- --write-mode=diff
  - cargo +nightly clippy -- -D clippy
  - cargo test
