language: rust
rust:
  - stable
  - 1.21.0
cache: cargo
services:
  - postgresql
before_install:
  - rustup install nightly
  - rustup run nightly cargo install --force rustfmt-nightly
  - nvm install 6
  - npm install -g yarn
  - cargo install --force diesel_cli
install:
  - cd web && yarn && cd -
before_script:
  - psql -c 'create database budgetron;' -U postgres
  - cp .env.travis .env
script:
  - cd web && yarn run webpack && cd -
  - rustup run nightly rustfmt --write-mode=diff src/lib.rs src/bin/budgetron.rs budgetronlib/src/lib.rs data_store/src/lib.rs
  - diesel migration run
  - cargo build
  - cargo test
