ignored_accounts = ["MORTGAGE LOAN"]

[categories]
"Auto Payment" = []
"Automobile" = ["Auto & Transport", "Service & Parts", "Gas & Fuel", "Parking"]
"Business" = ["Advertising","Business Services", "Office Supplies"]
"Cash" = ["ATM", "Cash & ATM"]
"Charity" = []
"Crowdfunding" = ["Kickstarter"]
"Education" = ["Tuition", "Student Loan"]
"Entertainment" = ["Movies & DVDs", "Music", "Arts", "Amusement"]
"Fees" = ["Fees & Charges", "Finance Charge", "Bank Fee", "Shipping", "ATM Fee"]
"Financial" = []
"Food & Dining" = [
  "Alcohol & Bars", "Fast Food", "Food Trucks", "DiningOut", "Delivery/Takeout",
  "Coffee Shops", "Restaurants", "Seamless"
]
"Gifts" = ["Gift"]
"Groceries" = []
"Health" = [
  "Pharmacy", "HealthDental", "Health & Fitness", "Dentist", "Doctor", "Gym",
  "HealthMedical", "BillsGym"
]
"Hobbies" = ["Books", "Books & Magazines", "Conventions"]
"Home Improvement" = []
"Household" = [
  "Furnishings", "Home Services", "Lawn & Garden", "Pets", "Home Supplies", "Home"
]
"Income" = ["Wages", "Paycheck", "Rental Income", "Bonus"]
"Insurance" = ["Auto Insurance", "BillsInsurance"]
"Interest" = ["Interest Income", "Dividends"]
"Investments" = ["Trade Commissions"]
"Kids" = ["Toys"]
"Legal" = []
"Online Subscriptions" = []
"Personal Care" = ["PersonalCare", "Hair", "Spa & Massage"]
"Mortgage & Rent" = ["BillsRent", "Rent", "BillsMortgage"]
"Shopping" = [
  "Amazon", "Clothing", "Sporting Goods", "Sports", "Costco", "Warehouse Clubs"
]
"Taxes" = ["State Tax", "Federal Tax"]
"Technology" = ["Computer/Video Games", "Electronics & Software", "VPS Hosting"]
"Television" = []
"Transfers" = ["Transfer", "Credit Card Payment"]
"Travel" = ["Hotel", "Public Transportation", "Rental Car & Taxi"]
"Uncategorized" = [
  "Transfer", "Check", "CreditMiscellaneous", "CreditNone", "CreditTransfer",
  "DebitMiscellaneous", "DebitNone", "DebitTransfer", "Reimbursement"
]
"Bills & Utilities" = [
  "Bills", "BillsCable", "BillsElectric", "BillsPhone", "Internet", "Utilities",
  "Security", "Mobile Phone", "BillsInternet"
]
"Hide" = ["Hide from Budgets & Trends", "Pending", "Exclusions", "Masterson Move-in", "Loan Payment", "Loan Insurance", "Loans"]

[budgets.monthly]
"Automobile" = 250.0
"Bills & Utilities" = 431.79
"Charity" = 34.0
"Entertainment" = 50.0
"Food & Dining" = 300.0
"Groceries" = 400.00
"Health" = 200.0
"Hobbies" = 100.0
"Insurance" = 321.0
"Mortgage & Rent" = 3635.63
"Online Subscriptions" = 50.0
"Shopping" = 115.0

[budgets.quarterly]
"Household" = 150.0

[budgets.yearly]
"Home Improvement" = 5000.0
