[[processor]]
hide_accounts = ["bad account"]

[[processor]]
transfer_horizon = 100

[[processor]]
[processor.categories]
"Auto Payment" = []
Automobile = ["Auto & Transport", "Gas & Fuel"]
Entertainment = ["Movies & DVDs", "Music", "Arts"]

[[processor]]
[processor.owners.joint]
account = ["Joint.*"]
category = ["Gas & Fuel"]
description = ["WASTE MGMT"]

[processor.owners.Person1]
account = ["Person1Account"]

[processor.owners.Person3]
description = ["OWNER 2"]

[[processor]]
owner_override = "Owner: (.*)"

[[processor]]
[processor.tags.essential]
description = ["COMCAST", "COSTCO WHSE"]
category = ["Home Projects"]

[processor.tags.recurring]
description = ["Hulu", "Google *Music"]

[processor.tags.ach]
description = ["ACH"]


[[report]]
name = "Rolling Budget"
skip_tags = ['essential', 'recurring', 'ach']

[report.config]
  type = "RollingBudget"
  split = 'joint'

  [report.config.amounts]
  '10/01/2017' = { Person1 = 100, Person2 = 100 }

[[report]]
name = "Cashflow"
config = { type = "Cashflow" }
by_month = true
