ignored_accounts = ["4431 Masterson Mortgage"]

[categories]
"Auto Payment" = []
"Automobile" = ["Auto & Transport", "Service & Parts", "Gas & Fuel", "Parking", "Transportation"]
"Business" = ["Advertising","Business Services", "Office Supplies"]
"Cash" = ["ATM", "Cash & ATM"]
"Charity" = []
"Crowdfunding" = ["Kickstarter"]
"Education" = ["Tuition", "Student Loan"]
"Entertainment" = ["Movies & DVDs", "Music", "Arts", "Amusement"]
"Fees" = ["Fees & Charges", "Finance Charge", "Bank Fee", "Shipping", "ATM Fee", "Service Fee"]
"Financial" = ["Financial Advisor"]
"Food & Dining" = [
  "Alcohol & Bars", "Fast Food", "Food Trucks", "DiningOut", "Delivery/Takeout",
  "Coffee Shops", "Restaurants", "Seamless", "Diningout"
]
"Gifts" = ["Gift"]
"Groceries" = []
"Health" = [
  "Pharmacy", "HealthDental", "Health & Fitness", "Dentist", "Doctor", "Gym",
  "HealthMedical", "BillsGym"
]
"Hobbies" = ["Books", "Books & Magazines", "Conventions"]
"Home Improvement" = []
"Household" = [
  "Furnishings", "Home Services", "Lawn & Garden", "Pets", "Home Supplies", "Home"
]
"Income" = ["Wages", "Paycheck", "Rental Income", "Bonus", "Personal"]
"Insurance" = ["Auto Insurance", "BillsInsurance"]
"Interest" = ["Interest Income", "Dividends"]
"Investments" = ["Trade Commissions"]
"Kids" = ["Toys"]
"Legal" = []
"Online Subscriptions" = []
"Personal Care" = ["PersonalCare", "Hair", "Spa & Massage"]
"Mortgage & Rent" = ["BillsRent", "Rent", "BillsMortgage"]
"Shopping" = [
  "Amazon", "Clothing", "Sporting Goods", "Sports", "Costco", "Warehouse Clubs"
]
"Taxes" = ["State Tax", "Federal Tax"]
"Technology" = ["Computer/Video Games", "Electronics & Software", "VPS Hosting"]
"Television" = []
"Transfers" = ["Transfer", "Credit Card Payment", "Payment", "Savings"]
"Travel" = ["Hotel", "Public Transportation", "Rental Car & Taxi"]
"Uncategorized" = [
  "Transfer", "Check", "CreditMiscellaneous", "CreditNone", "CreditTransfer",
  "DebitMiscellaneous", "DebitNone", "DebitTransfer", "Reimbursement", ""
]
"Bills & Utilities" = [
  "Bills", "BillsCable", "BillsElectric", "BillsPhone", "Internet", "Utilities",
  "Security", "Mobile Phone", "BillsInternet"
]
"Hide" = ["Hide from Budgets & Trends", "Pending", "Exclusions", "Masterson Move-in", "Loan Payment", "Loan Insurance", "Loans"]

[budgets.monthly]
"Automobile" = 250.0
"Bills & Utilities" = 431.79
"Charity" = 34.0
"Entertainment" = 50.0
"Food & Dining" = 300.0
"Groceries" = 400.00
"Health" = 200.0
"Hobbies" = 100.0
"Insurance" = 321.0
"Mortgage & Rent" = 3635.63
"Online Subscriptions" = 50.0
"Shopping" = 115.0

[budgets.quarterly]
"Household" = 150.0

[budgets.yearly]
"Home Improvement" = 5000.0

[tag.category.essential]
"description" = ["LIBERTY MUTUAL", "ADT SECURITY", "PGANDE", "BERKELEY BOWL", "VIRGIN MOBILE",
                 "GOLDEN STATE S", "EAST BAY MUD", "FASTRAK", "ZIPCAR", "PACIFIC GAS/ELEC",
                 "COSTCO WHSE", "JPMORGAN CHASE", "HOUSE OF PRODUCE", "EBMUD", "SAFEWAY", "LASTPASS",
                 "WASTE MGMT", "AmazonPrime Membership", "KASPERSKY", "NEARLYFREESPEECH.NET",
                 "COMCAST", "T-MOBILE", "TMOBILE", "GOOGLE STORA", "HOVER", "OAKLAND-ALARM PR",
                 "OAKLAND WEB PAYMENT"]

[tag.category.recurring]
"description" = ["Anfang", "Hulu", "Google *Music", "NETFLIX", "GOOGLE *Google Music", "EFF",
                 "ANFANG", "ACTBLUE", "Audible", "AUDIBLE", "AAA", "Duolingo", "Endomondo",
                 "PLAYSTATION NETWORK", "CR *CONSUMERREPORTS", "Netflix", "GOOGLE *DUOLINGO"]

[tag.category.tiny.range]
"low" = 0.0
"high" = 5.0

[tag.category.small.range]
"low" = 5.0
"high" = 25.0

[tag.category.medium.range]
"low" = 25.0
"high" = 125.0

[tag.category.big.range]
"low" = 125.0
"high" = 625.0

[tag.category.huge.range]
"low" = 625.0
"high" = 3125.0

[tag.category.massive.range]
"low" = 3125.0
"high" = 15625.0

[tag.category.colossal.range]
"low" = 15625.0
"high" = 1_000_000.0
