max_width = 100
array_width = 100
chain_one_line_max = 100
comment_width = 100
fn_call_width = 100
single_line_if_else_max_width = 100
struct_lit_width = 100
struct_variant_width = 100

match_block_trailing_comma = true
