// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'chipBag': string;
  'mainContent': string;
  'report': string;
  'reports': string;
  'spacer': string;
}
declare const cssExports: CssExports;
export = cssExports;
