// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'inner_table': string;
  'normal_row': string;
  'table': string;
}
declare const cssExports: CssExports;
export = cssExports;
