[package]
name = "budgetronlib"
version = "0.1.0"
authors = ["Zach Bush <zach@zmbush.com>"]
edition = "2018"

[dependencies]
chrono = "0.4.18"
serde = { version = "1.0.101", features = ["derive"] }
toml = "0.5.3"
csv = "1.1.1"
dirs = "2.0.2"
