[package]
name = "budgetronlib"
version = "0.1.0"
authors = ["Zach Bush <zach@zmbush.com>"]

[dependencies]
chrono = "0.4.9"
serde = "1.0.101"
serde_derive = "1.0.101"
toml = "0.5.3"
csv = "1.1.1"
dirs = "2.0.2"
