// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'category': string;
  'reportSection': string;
}
declare const cssExports: CssExports;
export = cssExports;
