[package]
name = "data_store"
version = "0.1.0"
authors = ["Zach Bush <zach@zmbush.com>"]

[dependencies]
diesel = { version = "*", features = ["chrono", "postgres"] }
diesel_codegen = { version = "*", features = ["postgres"] }
dotenv = "*"
chrono = "*"
