[package]
name = "transactor"
version = "0.1.0"
authors = ["Zach Bush <zach@zmbush.com>"]

[dependencies]
serde = "^1.0"
serde_derive = "*"
budgetronlib = { path = "../budgetronlib" }
log = "*"

[dependencies.csv]
git = "https://github.com/BurntSushi/rust-csv.git"
branch = "rewrite"
