// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'negative': string;
  'positive': string;
}
declare const cssExports: CssExports;
export = cssExports;
