// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'data': string;
  'graph': string;
  'main': string;
}
declare const cssExports: CssExports;
export = cssExports;
